# Generated by Django 4.1.1 on 2023-03-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_discription_contact_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('flavour', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('Address', models.TextField()),
            ],
        ),
    ]
